# Generated by Django 5.2.10 on 2026-02-05 06:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0002_alter_company_telegram_chat_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='company',
            name='telegram_chat_id',
            field=models.IntegerField(default=None, null=True, verbose_name='ID Telegram чата'),
        ),
    ]
