# Generated by Django 5.2.10 on 2026-02-05 10:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0004_alter_company_telegram_chat_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='company',
            name='telegram_chat_id',
            field=models.CharField(blank=True, default=None, max_length=255, null=True, verbose_name='ID Telegram чата'),
        ),
    ]