# Generated by Django 5.2.10 on 2026-02-10 04:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0005_alter_company_telegram_chat_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='report_file',
            field=models.FileField(blank=True, default=None, null=True, upload_to='reports/', verbose_name='Акт'),
        ),
    ]
