# Generated by Django 5.2.10 on 2026-02-12 05:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0006_company_report_file'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='company',
            name='report_file',
        ),
        migrations.AddField(
            model_name='company',
            name='report_file_from',
            field=models.FileField(blank=True, default=None, null=True, upload_to='reports/', verbose_name='Акт прием'),
        ),
        migrations.AddField(
            model_name='company',
            name='report_file_to',
            field=models.FileField(blank=True, default=None, null=True, upload_to='reports/', verbose_name='Акт выдача'),
        ),
    ]
