# Generated by Django 5.2 on 2026-07-15

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("companies", "0008_company_equipment_email_recipients"),
    ]

    operations = [
        migrations.AddField(
            model_name="company",
            name="api_key",
            field=models.CharField(
                blank=True,
                editable=False,
                max_length=64,
                null=True,
                unique=True,
                verbose_name="API-ключ",
            ),
        ),
    ]
