# Generated by Django 5.2.11 on 2026-07-14

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("devices", "0002_report"),
    ]

    operations = [
        migrations.CreateModel(
            name="EquipmentNotificationSettings",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("email_to", models.CharField(blank=True, max_length=1000, verbose_name="Кому")),
                ("email_cc", models.CharField(blank=True, max_length=1000, verbose_name="Копия")),
            ],
            options={
                "verbose_name": "Настройки уведомлений об оборудовании",
                "verbose_name_plural": "Настройки уведомлений об оборудовании",
            },
        ),
    ]
