# Generated by Django 5.2 on 2026-07-15

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("devices", "0004_remove_equipmentnotificationsettings"),
    ]

    operations = [
        migrations.AddField(
            model_name="equipment",
            name="bitlocker_recovery_key",
            field=models.CharField(blank=True, max_length=64, verbose_name="Ключ восстановления BitLocker"),
        ),
    ]
